const translations = {
    en: {
        // Navigation
        'nav-home': 'Home',
        'nav-weather': 'Weather',
        'nav-market': 'Storage Guide',
        'nav-calendar': 'Crop Advisor',
        'nav-profit': 'Profit Predictor',
        'nav-inputs': 'Farm Inputs',
        'nav-schemes': 'Schemes',
        
        // Hero
        'hero-title': 'Smart Farming for Better Future',
        'hero-subtitle': 'Empowering farmers with technology and knowledge',
        
        // Features
        'feature-weather': 'Weather Forecast',
        'feature-weather-desc': 'Real-time weather updates',
        'feature-market': 'Storage Guide',
        'feature-market-desc': 'Proper crop storage tips',
        'feature-calendar': 'Crop Advisor',
        'feature-calendar-desc': 'Personalized crop recommendations',
        'feature-profit': 'Profit Calculator',
        'feature-profit-desc': 'Estimate your earnings',
        'feature-inputs': 'Farm Inputs',
        'feature-inputs-desc': 'Seeds, fertilizers & more',
        'feature-schemes': 'Govt Schemes',
        'feature-schemes-desc': 'Benefits & subsidies',
        
        // Weather
        'weather-title': 'Weather Forecast',
        'weather-location': 'Enter location',
        
        // Market
        'market-title': 'Market Prices',
        'market-crop': 'Crop',
        'market-price': 'Price (₹/Quintal)',
        'market-location': 'Location',
        'market-trend': 'Trend',
        
        // Crop Calendar
        'calendar-title': 'Personalized Crop Advisor',
        'crop-rice': 'Rice',
        'crop-wheat': 'Wheat',
        'crop-cotton': 'Cotton',
        'crop-sugarcane': 'Sugarcane',
        'crop-maize': 'Maize',
        'crop-soybean': 'Soybean',
        'crop-groundnut': 'Groundnut',
        'crop-chickpea': 'Chickpea',
        'crop-mustard': 'Mustard',
        'crop-onion': 'Onion',
        'crop-potato': 'Potato',
        'crop-tomato': 'Tomato',
        'crop-chilli': 'Chilli',
        'crop-turmeric': 'Turmeric',
        'crop-banana': 'Banana',
        
        // Profit Calculator
        'profit-title': 'Farm Profit Predictor',
        'profit-calculator': 'Profit Calculator',
        'profit-land': 'Land Area (Acres)',
        'profit-crop': 'Crop Name',
        'profit-yield': 'Expected Yield (Quintal/Acre)',
        'profit-price': 'Market Price (₹/Quintal)',
        'profit-calculate': 'Calculate',
        'profit-production': 'Total Production:',
        'profit-revenue': 'Estimated Revenue:',
        'profit-profit': 'Expected Profit:',
        'farm-calculator': 'Farm Calculator',
        
        // Farm Inputs
        'inputs-title': 'Farm Inputs',
        'inputs-seeds': 'Seeds',
        'inputs-seeds-desc': 'High-quality certified seeds',
        'inputs-fertilizers': 'Fertilizers',
        'inputs-fertilizers-desc': 'Organic & chemical fertilizers',
        'inputs-pesticides': 'Pesticides',
        'inputs-pesticides-desc': 'Safe pest control solutions',
        'inputs-irrigation': 'Irrigation Equipment',
        'inputs-irrigation-desc': 'Drip & sprinkler systems',
        'inputs-machinery': 'Agricultural Machinery',
        'inputs-machinery-desc': 'Modern farming equipment',
        'inputs-learn': 'Learn More',
        
        // Government Schemes
        'schemes-title': 'Government Schemes',
        'scheme-pmkisan': 'PM-KISAN',
        'scheme-pmfby': 'PM Fasal Bima Yojana',
        'scheme-soil': 'Soil Health Card',
        'schemes-eligibility': 'Eligibility:',
        'schemes-documents': 'Required Documents:',
        'schemes-benefits': 'Benefits:',
        
        // Seeds Modal
        'modal-seeds-title': '🌱 Seeds Information',
        'modal-fertilizers-title': '🧪 Fertilizers Information',
        'modal-pesticides-title': '🐛 Pesticides Information',
        'modal-irrigation-title': '💧 Irrigation Equipment',
        'modal-machinery-title': '🚜 Agricultural Machinery',
        'modal-uses': 'Uses:',
        'modal-season': 'Season:',
        'modal-tips': '💡 Tips:',
        'modal-safety': '⚠️ Safety:',
        'modal-maintenance': '💡 Maintenance:',
        'seed-rice': 'Rice Seeds',
        'seed-wheat': 'Wheat Seeds',
        'seed-cotton': 'Cotton Seeds',
        'seed-maize': 'Maize Seeds',
        'seed-vegetable': 'Vegetable Seeds',
        'seed-pulses': 'Pulses Seeds',
        'seed-rice-use': 'Main staple crop, high yield varieties',
        'seed-wheat-use': 'Flour production, high protein',
        'seed-cotton-use': 'Textile industry, oil production',
        'seed-maize-use': 'Food, animal feed, industrial',
        'seed-veg-use': 'Tomato, onion, potato cultivation',
        'seed-pulses-use': 'Protein-rich food, soil enrichment',
        'season-yearround': 'Year-round',
        'seed-tip1': 'Buy certified seeds from authorized dealers',
        'seed-tip2': 'Check seed germination rate before purchase',
        'seed-tip3': 'Store seeds in cool, dry place',
        'seed-tip4': 'Choose varieties suitable for your soil',
        
        // PM-KISAN Scheme Details
        'pmkisan-desc': 'Pradhan Mantri Kisan Samman Nidhi - Direct income support of ₹6000/year',
        'pmkisan-elig1': 'All landholding farmers',
        'pmkisan-elig2': 'Valid Aadhaar card',
        'pmkisan-doc1': 'Aadhaar Card',
        'pmkisan-doc2': 'Bank Account Details',
        'pmkisan-doc3': 'Land Records',
        
        // PMFBY Scheme Details
        'pmfby-desc': 'Pradhan Mantri Fasal Bima Yojana - Crop insurance scheme',
        'pmfby-elig1': 'All farmers growing notified crops',
        'pmfby-elig2': 'Sharecroppers & tenant farmers',
        'pmfby-ben1': 'Coverage for crop loss',
        'pmfby-ben2': 'Low premium rates',
        
        // Soil Health Card Details
        'soil-desc': 'Get detailed soil analysis and recommendations',
        'soil-elig1': 'All farmers',
        'soil-elig2': 'Free of cost',
        'soil-ben1': 'Soil nutrient status',
        'soil-ben2': 'Fertilizer recommendations',
        
        // Buttons
        'btn-watch': 'Watch on YouTube',
        'btn-apply': 'Apply Online',
        
        // Fertilizers Modal
        'fert-urea': 'Urea (46% N)',
        'fert-urea-use': 'Provides nitrogen for leaf growth and green color',
        'fert-urea-app': '50-100 kg per acre',
        'fert-dap': 'DAP (18-46-0)',
        'fert-dap-use': 'Rich in phosphorus, promotes root development',
        'fert-dap-app': '40-80 kg per acre',
        'fert-mop': 'MOP (Potash)',
        'fert-mop-use': 'Potassium for fruit quality and disease resistance',
        'fert-mop-app': '30-60 kg per acre',
        'fert-npk': 'NPK (19-19-19)',
        'fert-npk-use': 'Balanced nutrition for overall plant growth',
        'fert-npk-app': '50-100 kg per acre',
        'fert-compost': 'Compost',
        'fert-compost-use': 'Organic matter, improves soil structure',
        'fert-compost-app': '2-5 tons per acre',
        'fert-vermi': 'Vermicompost',
        'fert-vermi-use': 'Rich organic fertilizer, enhances soil fertility',
        'fert-vermi-app': '1-2 tons per acre',
        'fert-zinc': 'Zinc Sulphate',
        'fert-zinc-use': 'Corrects zinc deficiency, improves crop yield',
        'fert-zinc-app': '10-25 kg per acre',
        'fert-calcium': 'Calcium Nitrate',
        'fert-calcium-use': 'Provides calcium and nitrogen, prevents blossom end rot',
        'fert-calcium-app': '20-40 kg per acre',
        'fert-sulphur': 'Sulphur',
        'fert-sulphur-use': 'Essential for protein synthesis, improves oil content',
        'fert-sulphur-app': '15-30 kg per acre',
        'fert-boron': 'Boron',
        'fert-boron-use': 'Improves flowering, fruit setting, and seed formation',
        'fert-boron-app': '5-10 kg per acre',
        'fert-tip1': 'Soil test before applying',
        'fert-tip2': 'Apply at right time',
        'fert-tip3': 'Mix organic & chemical',
        'fert-tip4': 'Avoid over-fertilization',
        'modal-application': 'Application:',
        
        // Pesticides Modal
        'pest-chlorpyrifos': 'Chlorpyrifos',
        'pest-chlorpyrifos-use': 'Controls termites, aphids, and soil insects',
        'pest-chlorpyrifos-app': '400-500 ml per acre',
        'pest-imidacloprid': 'Imidacloprid',
        'pest-imidacloprid-use': 'Effective against sucking pests like whiteflies',
        'pest-imidacloprid-app': '100-150 ml per acre',
        'pest-cypermethrin': 'Cypermethrin',
        'pest-cypermethrin-use': 'Controls bollworms, caterpillars, and beetles',
        'pest-cypermethrin-app': '200-300 ml per acre',
        'pest-neem': 'Neem Oil',
        'pest-neem-use': 'Organic pesticide for various pests and diseases',
        'pest-neem-app': '1-2 liters per acre',
        'pest-mancozeb': 'Mancozeb',
        'pest-mancozeb-use': 'Fungicide for blight, rust, and leaf spots',
        'pest-mancozeb-app': '400-600 gm per acre',
        'pest-carbendazim': 'Carbendazim',
        'pest-carbendazim-use': 'Broad-spectrum fungicide for seed treatment',
        'pest-carbendazim-app': '200-250 gm per acre',
        'pest-bt': 'Bacillus Thuringiensis',
        'pest-bt-use': 'Biological pesticide for caterpillars and larvae',
        'pest-bt-app': '200-400 gm per acre',
        'pest-profenofos': 'Profenofos',
        'pest-profenofos-use': 'Controls bollworms, jassids, and thrips',
        'pest-profenofos-app': '400-500 ml per acre',
        'pest-glyphosate': 'Glyphosate',
        'pest-glyphosate-use': 'Herbicide for weed control in crops',
        'pest-glyphosate-app': '1-1.5 liters per acre',
        'pest-acetamiprid': 'Acetamiprid',
        'pest-acetamiprid-use': 'Controls aphids, jassids, and whiteflies',
        'pest-acetamiprid-app': '60-80 gm per acre',
        'pest-tip1': 'Wear protective gear',
        'pest-tip2': 'Read label instructions',
        'pest-tip3': 'Spray early morning/evening',
        'pest-tip4': 'Keep away from children',
        
        // Irrigation Modal
        'irr-drip': 'Drip Irrigation',
        'irr-drip-use': 'Water-efficient system for row crops and orchards',
        'irr-drip-ben': 'Saves 40-70% water, reduces weed growth',
        'irr-sprinkler': 'Sprinkler System',
        'irr-sprinkler-use': 'Suitable for all crops, especially vegetables',
        'irr-sprinkler-ben': 'Uniform water distribution, saves labor',
        'irr-micro': 'Micro Sprinkler',
        'irr-micro-use': 'Ideal for fruit trees and plantation crops',
        'irr-micro-ben': 'Low pressure requirement, covers large area',
        'irr-submersible': 'Submersible Pump',
        'irr-submersible-use': 'Deep well water extraction for irrigation',
        'irr-submersible-ben': 'High efficiency, low maintenance',
        'irr-centrifugal': 'Centrifugal Pump',
        'irr-centrifugal-use': 'Surface water pumping for irrigation',
        'irr-centrifugal-ben': 'Cost-effective, easy to operate',
        'irr-solar': 'Solar Pump',
        'irr-solar-use': 'Eco-friendly irrigation using solar energy',
        'irr-solar-ben': 'Zero electricity cost, environment friendly',
        'irr-pipes': 'PVC Pipes',
        'irr-pipes-use': 'Water distribution in irrigation systems',
        'irr-pipes-ben': 'Durable, corrosion-resistant, lightweight',
        'irr-filter': 'Water Filter',
        'irr-filter-use': 'Removes impurities from irrigation water',
        'irr-filter-ben': 'Prevents clogging, extends system life',
        'irr-timer': 'Irrigation Timer',
        'irr-timer-use': 'Automated irrigation scheduling',
        'irr-timer-ben': 'Saves time, ensures timely watering',
        'irr-meter': 'Water Meter',
        'irr-meter-use': 'Measures water usage in irrigation',
        'irr-meter-ben': 'Helps optimize water consumption',
        'irr-tip1': 'Choose based on crop type',
        'irr-tip2': 'Regular maintenance',
        'irr-tip3': 'Use drip for water saving',
        'irr-tip4': 'Irrigate morning/evening',
        'modal-benefits': 'Benefits:',
        
        // Machinery Modal
        'mach-tractor': 'Tractor',
        'mach-tractor-use': 'Primary power source for various farm operations',
        'mach-tractor-ben': 'Versatile, reduces labor, increases efficiency',
        'mach-rotavator': 'Rotavator',
        'mach-rotavator-use': 'Soil preparation, mixing crop residue',
        'mach-rotavator-ben': 'Saves time, improves soil structure',
        'mach-seeddrill': 'Seed Drill',
        'mach-seeddrill-use': 'Precise seed sowing at uniform depth',
        'mach-seeddrill-ben': 'Uniform germination, saves seeds',
        'mach-sprayer': 'Power Sprayer',
        'mach-sprayer-use': 'Pesticide and fertilizer application',
        'mach-sprayer-ben': 'Uniform coverage, saves chemicals',
        'mach-harvester': 'Harvester',
        'mach-harvester-use': 'Crop harvesting and threshing',
        'mach-harvester-ben': 'Fast harvesting, reduces grain loss',
        'mach-cultivator': 'Cultivator',
        'mach-cultivator-use': 'Weed control and soil aeration',
        'mach-cultivator-ben': 'Improves soil health, removes weeds',
        'mach-thresher': 'Thresher',
        'mach-thresher-use': 'Separating grains from crop stalks',
        'mach-thresher-ben': 'Fast processing, reduces manual labor',
        'mach-chaff': 'Chaff Cutter',
        'mach-chaff-use': 'Cutting fodder for livestock',
        'mach-chaff-ben': 'Easy feeding, reduces wastage',
        'mach-dryer': 'Grain Dryer',
        'mach-dryer-use': 'Drying harvested grains for storage',
        'mach-dryer-ben': 'Prevents spoilage, maintains quality',
        'mach-mulcher': 'Mulcher',
        'mach-mulcher-use': 'Shredding crop residue and weeds',
        'mach-mulcher-ben': 'Soil enrichment, moisture retention',
        'mach-tip1': 'Regular servicing required',
        'mach-tip2': 'Proper operator training',
        'mach-tip3': 'Store in dry place',
        'mach-tip4': 'Check before each use',
        
        // Calendar Legend
        'legend-sowing': 'Sowing',
        'legend-fertilizer': 'Fertilizer',
        'legend-harvest': 'Harvest',

        // Crop Advisor
        'advisor-state': 'Select State',
        'advisor-month': 'Current Month',
        'advisor-soil': 'Soil Type',
        'advisor-placeholder': 'Select your state and soil type to get personalized crop recommendations'
    },
    
    hi: {
        // Navigation
        'nav-home': 'होम',
        'nav-weather': 'मौसम',
        'nav-market': 'भंडारण गाइड',
        'nav-calendar': 'फसल सलाहकार',
        'nav-profit': 'लाभ कैलकुलेटर',
        'nav-inputs': 'कृषि सामग्री',
        'nav-schemes': 'योजनाएं',
        
        // Hero
        'hero-title': 'बेहतर भविष्य के लिए स्मार्ट खेती',
        'hero-subtitle': 'प्रौद्योगिकी और ज्ञान से किसानों को सशक्त बनाना',
        
        // Features
        'feature-weather': 'मौसम पूर्वानुमान',
        'feature-weather-desc': 'वास्तविक समय मौसम अपडेट',
        'feature-market': 'भंडारण गाइड',
        'feature-market-desc': 'उचित फसल भंडारण सुझाव',
        'feature-calendar': 'फसल सलाहकार',
        'feature-calendar-desc': 'व्यक्तिगत फसल सिफारिशें',
        'feature-profit': 'लाभ कैलकुलेटर',
        'feature-profit-desc': 'अपनी कमाई का अनुमान लगाएं',
        'feature-inputs': 'कृषि सामग्री',
        'feature-inputs-desc': 'बीज, उर्वरक और अधिक',
        'feature-schemes': 'सरकारी योजनाएं',
        'feature-schemes-desc': 'लाभ और सब्सिडी',
        
        // Weather
        'weather-title': 'मौसम पूर्वानुमान',
        'weather-location': 'स्थान दर्ज करें',
        
        // Market
        'market-title': 'बाजार मूल्य',
        'market-crop': 'फसल',
        'market-price': 'मूल्य (₹/क्विंटल)',
        'market-location': 'स्थान',
        'market-trend': 'रुझान',
        
        // Crop Calendar
        'calendar-title': 'व्यक्तिगत फसल सलाहकार',
        'crop-rice': 'धान',
        'crop-wheat': 'गेहूं',
        'crop-cotton': 'कपास',
        'crop-sugarcane': 'गन्ना',
        'crop-maize': 'मक्का',
        'crop-soybean': 'सोयाबीन',
        'crop-groundnut': 'मूंगफली',
        'crop-chickpea': 'चना',
        'crop-mustard': 'सरसों',
        'crop-onion': 'प्याज',
        'crop-potato': 'आलू',
        'crop-tomato': 'टमाटर',
        'crop-chilli': 'मिर्च',
        'crop-turmeric': 'हल्दी',
        'crop-banana': 'केला',
        
        // Profit Calculator
        'profit-title': 'कृषि लाभ भविष्यवक्ता',
        'profit-calculator': 'लाभ कैलकुलेटर',
        'profit-land': 'भूमि क्षेत्र (एकड़)',
        'profit-crop': 'फसल का नाम',
        'profit-yield': 'अपेक्षित उपज (क्विंटल/एकड़)',
        'profit-price': 'बाजार मूल्य (₹/क्विंटल)',
        'profit-calculate': 'गणना करें',
        'profit-production': 'कुल उत्पादन:',
        'profit-revenue': 'अनुमानित राजस्व:',
        'profit-profit': 'अपेक्षित लाभ:',
        'farm-calculator': 'कृषि कैलकुलेटर',
        
        // Farm Inputs
        'inputs-title': 'कृषि सामग्री',
        'inputs-seeds': 'बीज',
        'inputs-seeds-desc': 'उच्च गुणवत्ता वाले प्रमाणित बीज',
        'inputs-fertilizers': 'उर्वरक',
        'inputs-fertilizers-desc': 'जैविक और रासायनिक उर्वरक',
        'inputs-pesticides': 'कीटनाशक',
        'inputs-pesticides-desc': 'सुरक्षित कीट नियंत्रण समाधान',
        'inputs-irrigation': 'सिंचाई उपकरण',
        'inputs-irrigation-desc': 'ड्रिप और स्प्रिंकलर सिस्टम',
        'inputs-machinery': 'कृषि मशीनरी',
        'inputs-machinery-desc': 'आधुनिक कृषि उपकरण',
        'inputs-learn': 'और जानें',
        
        // Government Schemes
        'schemes-title': 'सरकारी योजनाएं',
        'scheme-pmkisan': 'पीएम-किसान',
        'scheme-pmfby': 'पीएम फसल बीमा योजना',
        'scheme-soil': 'मृदा स्वास्थ्य कार्ड',
        'schemes-eligibility': 'पात्रता:',
        'schemes-documents': 'आवश्यक दस्तावेज:',
        'schemes-benefits': 'लाभ:',
        
        // Seeds Modal
        'modal-seeds-title': '🌱 बीज जानकारी',
        'modal-fertilizers-title': '🧪 उर्वरक जानकारी',
        'modal-pesticides-title': '🐛 कीटनाशक जानकारी',
        'modal-irrigation-title': '💧 सिंचाई उपकरण',
        'modal-machinery-title': '🚜 कृषि मशीनरी',
        'modal-uses': 'उपयोग:',
        'modal-season': 'मौसम:',
        'modal-tips': '💡 सुझाव:',
        'modal-safety': '⚠️ सुरक्षा:',
        'modal-maintenance': '💡 रखरखाव:',
        'seed-rice': 'धान के बीज',
        'seed-wheat': 'गेहूं के बीज',
        'seed-cotton': 'कपास के बीज',
        'seed-maize': 'मक्का के बीज',
        'seed-vegetable': 'सब्जी के बीज',
        'seed-pulses': 'दाल के बीज',
        'seed-rice-use': 'मुख्य खाद्य फसल, उच्च उपज किस्में',
        'seed-wheat-use': 'आटा उत्पादन, उच्च प्रोटीन',
        'seed-cotton-use': 'कपड़ा उद्योग, तेल उत्पादन',
        'seed-maize-use': 'भोजन, पशु चारा, औद्योगिक',
        'seed-veg-use': 'टमाटर, प्याज, आलू की खेती',
        'seed-pulses-use': 'प्रोटीन युक्त भोजन, मिट्टी संवर्धन',
        'season-yearround': 'साल भर',
        'seed-tip1': 'अधिकृत डीलरों से प्रमाणित बीज खरीदें',
        'seed-tip2': 'खरीदने से पहले अंकुरण दर जांचें',
        'seed-tip3': 'बीजों को ठंडी, सूखी जगह में रखें',
        'seed-tip4': 'अपनी मिट्टी के लिए उपयुक्त किस्में चुनें',
        
        // PM-KISAN Scheme Details
        'pmkisan-desc': 'प्रधानमंत्री किसान सम्मान निधि - ₹6000/वर्ष की प्रत्यक्ष आय सहायता',
        'pmkisan-elig1': 'सभी भूमिधारक किसान',
        'pmkisan-elig2': 'वैध आधार कार्ड',
        'pmkisan-doc1': 'आधार कार्ड',
        'pmkisan-doc2': 'बैंक खाता विवरण',
        'pmkisan-doc3': 'भूमि रिकॉर्ड',
        
        // PMFBY Scheme Details
        'pmfby-desc': 'प्रधानमंत्री फसल बीमा योजना - फसल बीमा योजना',
        'pmfby-elig1': 'अधिसूचित फसलें उगाने वाले सभी किसान',
        'pmfby-elig2': 'बटाईदार और किरायेदार किसान',
        'pmfby-ben1': 'फसल नुकसान के लिए कवरेज',
        'pmfby-ben2': 'कम प्रीमियम दरें',
        
        // Soil Health Card Details
        'soil-desc': 'विस्तृत मिट्टी विश्लेषण और सिफारिशें प्राप्त करें',
        'soil-elig1': 'सभी किसान',
        'soil-elig2': 'निःशुल्क',
        'soil-ben1': 'मिट्टी पोषक तत्व स्थिति',
        'soil-ben2': 'उर्वरक सिफारिशें',
        
        // Buttons
        'btn-watch': 'YouTube पर देखें',
        'btn-apply': 'ऑनलाइन आवेदन करें',
        
        // Fertilizers Modal
        'fert-urea': 'यूरिया (46% N)',
        'fert-urea-use': 'पत्ती वृद्धि और हरे रंग के लिए नाइट्रोजन प्रदान करता है',
        'fert-urea-app': '50-100 किग्रा प्रति एकड़',
        'fert-dap': 'डीएपी (18-46-0)',
        'fert-dap-use': 'फास्फोरस से भरपूर, जड़ विकास को बढ़ावा देता है',
        'fert-dap-app': '40-80 किग्रा प्रति एकड़',
        'fert-mop': 'एमओपी (पोटाश)',
        'fert-mop-use': 'फल गुणवत्ता और रोग प्रतिरोध के लिए पोटेशियम',
        'fert-mop-app': '30-60 किग्रा प्रति एकड़',
        'fert-npk': 'एनपीके (19-19-19)',
        'fert-npk-use': 'समग्र पौधे की वृद्धि के लिए संतुलित पोषण',
        'fert-npk-app': '50-100 किग्रा प्रति एकड़',
        'fert-compost': 'कम्पोस्ट',
        'fert-compost-use': 'जैविक पदार्थ, मिट्टी की संरचना में सुधार करता है',
        'fert-compost-app': '2-5 टन प्रति एकड़',
        'fert-vermi': 'वर्मीकम्पोस्ट',
        'fert-vermi-use': 'समृद्ध जैविक उर्वरक, मिट्टी की उर्वरता बढ़ाता है',
        'fert-vermi-app': '1-2 टन प्रति एकड़',
        'fert-zinc': 'जिंक सल्फेट',
        'fert-zinc-use': 'जिंक की कमी को ठीक करता है, फसल उपज में सुधार करता है',
        'fert-zinc-app': '10-25 किग्रा प्रति एकड़',
        'fert-calcium': 'कैल्शियम नाइट्रेट',
        'fert-calcium-use': 'कैल्शियम और नाइट्रोजन प्रदान करता है, फूल सड़न को रोकता है',
        'fert-calcium-app': '20-40 किग्रा प्रति एकड़',
        'fert-sulphur': 'सल्फर',
        'fert-sulphur-use': 'प्रोटीन संश्लेषण के लिए आवश्यक, तेल सामग्री में सुधार करता है',
        'fert-sulphur-app': '15-30 किग्रा प्रति एकड़',
        'fert-boron': 'बोरॉन',
        'fert-boron-use': 'फूल, फल सेटिंग और बीज निर्माण में सुधार करता है',
        'fert-boron-app': '5-10 किग्रा प्रति एकड़',
        'fert-tip1': 'लगाने से पहले मिट्टी परीक्षण करें',
        'fert-tip2': 'सही समय पर लगाएं',
        'fert-tip3': 'जैविक और रासायनिक मिश्रण करें',
        'fert-tip4': 'अधिक उर्वरक से बचें',
        'modal-application': 'अनुप्रयोग:',
        
        // Pesticides Modal
        'pest-chlorpyrifos': 'क्लोरपाइरीफॉस',
        'pest-chlorpyrifos-use': 'दीमक, एफिड्स और मिट्टी के कीड़ों को नियंत्रित करता है',
        'pest-chlorpyrifos-app': '400-500 मिली प्रति एकड़',
        'pest-imidacloprid': 'इमिडाक्लोप्रिड',
        'pest-imidacloprid-use': 'सफेद मक्खी जैसे चूसने वाले कीटों के खिलाफ प्रभावी',
        'pest-imidacloprid-app': '100-150 मिली प्रति एकड़',
        'pest-cypermethrin': 'साइपरमेथ्रिन',
        'pest-cypermethrin-use': 'बॉलवर्म, कैटरपिलर और बीटल को नियंत्रित करता है',
        'pest-cypermethrin-app': '200-300 मिली प्रति एकड़',
        'pest-neem': 'नीम का तेल',
        'pest-neem-use': 'विभिन्न कीटों और बीमारियों के लिए जैविक कीटनाशक',
        'pest-neem-app': '1-2 लीटर प्रति एकड़',
        'pest-mancozeb': 'मैनकोजेब',
        'pest-mancozeb-use': 'झुलसा, जंग और पत्ती के धब्बों के लिए फफूंदनाशक',
        'pest-mancozeb-app': '400-600 ग्राम प्रति एकड़',
        'pest-carbendazim': 'कार्बेन्डाजिम',
        'pest-carbendazim-use': 'बीज उपचार के लिए व्यापक स्पेक्ट्रम फफूंदनाशक',
        'pest-carbendazim-app': '200-250 ग्राम प्रति एकड़',
        'pest-bt': 'बैसिलस थुरिंजिएन्सिस',
        'pest-bt-use': 'कैटरपिलर और लार्वा के लिए जैविक कीटनाशक',
        'pest-bt-app': '200-400 ग्राम प्रति एकड़',
        'pest-profenofos': 'प्रोफेनोफॉस',
        'pest-profenofos-use': 'बॉलवर्म, जैसिड और थ्रिप्स को नियंत्रित करता है',
        'pest-profenofos-app': '400-500 मिली प्रति एकड़',
        'pest-glyphosate': 'ग्लाइफोसेट',
        'pest-glyphosate-use': 'फसलों में खरपतवार नियंत्रण के लिए शाकनाशी',
        'pest-glyphosate-app': '1-1.5 लीटर प्रति एकड़',
        'pest-acetamiprid': 'एसिटामिप्रिड',
        'pest-acetamiprid-use': 'एफिड्स, जैसिड और सफेद मक्खी को नियंत्रित करता है',
        'pest-acetamiprid-app': '60-80 ग्राम प्रति एकड़',
        'pest-tip1': 'सुरक्षा उपकरण पहनें',
        'pest-tip2': 'लेबल निर्देश पढ़ें',
        'pest-tip3': 'सुबह/शाम छिड़काव करें',
        'pest-tip4': 'बच्चों से दूर रखें',
        
        // Irrigation Modal
        'irr-drip': 'ड्रिप सिंचाई',
        'irr-drip-use': 'पंक्ति फसलों और बागों के लिए जल-कुशल प्रणाली',
        'irr-drip-ben': '40-70% पानी बचाता है, खरपतवार वृद्धि कम करता है',
        'irr-sprinkler': 'स्प्रिंकलर सिस्टम',
        'irr-sprinkler-use': 'सभी फसलों के लिए उपयुक्त, विशेष रूप से सब्जियां',
        'irr-sprinkler-ben': 'समान जल वितरण, श्रम बचाता है',
        'irr-micro': 'माइक्रो स्प्रिंकलर',
        'irr-micro-use': 'फलों के पेड़ों और बागान फसलों के लिए आदर्श',
        'irr-micro-ben': 'कम दबाव की आवश्यकता, बड़े क्षेत्र को कवर करता है',
        'irr-submersible': 'सबमर्सिबल पंप',
        'irr-submersible-use': 'सिंचाई के लिए गहरे कुएं से पानी निकालना',
        'irr-submersible-ben': 'उच्च दक्षता, कम रखरखाव',
        'irr-centrifugal': 'सेंट्रीफ्यूगल पंप',
        'irr-centrifugal-use': 'सिंचाई के लिए सतही जल पंपिंग',
        'irr-centrifugal-ben': 'लागत प्रभावी, संचालित करने में आसान',
        'irr-solar': 'सोलर पंप',
        'irr-solar-use': 'सौर ऊर्जा का उपयोग करके पर्यावरण के अनुकूल सिंचाई',
        'irr-solar-ben': 'शून्य बिजली लागत, पर्यावरण के अनुकूल',
        'irr-pipes': 'पीवीसी पाइप',
        'irr-pipes-use': 'सिंचाई प्रणालियों में जल वितरण',
        'irr-pipes-ben': 'टिकाऊ, जंग प्रतिरोधी, हल्का',
        'irr-filter': 'वाटर फिल्टर',
        'irr-filter-use': 'सिंचाई के पानी से अशुद्धियों को हटाता है',
        'irr-filter-ben': 'रुकावट को रोकता है, सिस्टम जीवन बढ़ाता है',
        'irr-timer': 'सिंचाई टाइमर',
        'irr-timer-use': 'स्वचालित सिंचाई शेड्यूलिंग',
        'irr-timer-ben': 'समय बचाता है, समय पर पानी सुनिश्चित करता है',
        'irr-meter': 'वाटर मीटर',
        'irr-meter-use': 'सिंचाई में पानी के उपयोग को मापता है',
        'irr-meter-ben': 'पानी की खपत को अनुकूलित करने में मदद करता है',
        'irr-tip1': 'फसल के प्रकार के आधार पर चुनें',
        'irr-tip2': 'नियमित रखरखाव',
        'irr-tip3': 'पानी बचाने के लिए ड्रिप का उपयोग करें',
        'irr-tip4': 'सुबह/शाम सिंचाई करें',
        'modal-benefits': 'लाभ:',
        
        // Machinery Modal
        'mach-tractor': 'ट्रैक्टर',
        'mach-tractor-use': 'विभिन्न कृषि कार्यों के लिए प्राथमिक शक्ति स्रोत',
        'mach-tractor-ben': 'बहुमुखी, श्रम कम करता है, दक्षता बढ़ाता है',
        'mach-rotavator': 'रोटावेटर',
        'mach-rotavator-use': 'मिट्टी की तैयारी, फसल अवशेष मिश्रण',
        'mach-rotavator-ben': 'समय बचाता है, मिट्टी की संरचना में सुधार करता है',
        'mach-seeddrill': 'सीड ड्रिल',
        'mach-seeddrill-use': 'समान गहराई पर सटीक बीज बुवाई',
        'mach-seeddrill-ben': 'समान अंकुरण, बीज बचाता है',
        'mach-sprayer': 'पावर स्प्रेयर',
        'mach-sprayer-use': 'कीटनाशक और उर्वरक अनुप्रयोग',
        'mach-sprayer-ben': 'समान कवरेज, रसायन बचाता है',
        'mach-harvester': 'हार्वेस्टर',
        'mach-harvester-use': 'फसल की कटाई और थ्रेशिंग',
        'mach-harvester-ben': 'तेज कटाई, अनाज की हानि कम करता है',
        'mach-cultivator': 'कल्टीवेटर',
        'mach-cultivator-use': 'खरपतवार नियंत्रण और मिट्टी वातन',
        'mach-cultivator-ben': 'मिट्टी के स्वास्थ्य में सुधार, खरपतवार हटाता है',
        'mach-thresher': 'थ्रेशर',
        'mach-thresher-use': 'फसल के डंठल से अनाज अलग करना',
        'mach-thresher-ben': 'तेज प्रसंस्करण, मैनुअल श्रम कम करता है',
        'mach-chaff': 'चारा काटने की मशीन',
        'mach-chaff-use': 'पशुओं के लिए चारा काटना',
        'mach-chaff-ben': 'आसान खिलाना, बर्बादी कम करता है',
        'mach-dryer': 'ग्रेन ड्रायर',
        'mach-dryer-use': 'भंडारण के लिए कटे हुए अनाज को सुखाना',
        'mach-dryer-ben': 'खराब होने से रोकता है, गुणवत्ता बनाए रखता है',
        'mach-mulcher': 'मल्चर',
        'mach-mulcher-use': 'फसल अवशेष और खरपतवार को काटना',
        'mach-mulcher-ben': 'मिट्टी संवर्धन, नमी प्रतिधारण',
        'mach-tip1': 'नियमित सर्विसिंग आवश्यक',
        'mach-tip2': 'उचित ऑपरेटर प्रशिक्षण',
        'mach-tip3': 'सूखी जगह में स्टोर करें',
        'mach-tip4': 'प्रत्येक उपयोग से पहले जांचें',
        
        // Calendar Legend
        'legend-sowing': 'बुवाई',
        'legend-fertilizer': 'उर्वरक',
        'legend-harvest': 'कटाई',

        // Crop Advisor
        'advisor-state': 'राज्य चुनें',
        'advisor-month': 'वर्तमान माह',
        'advisor-soil': 'मिट्टी का प्रकार',
        'advisor-placeholder': 'व्यक्तिगत फसल सिफारिशें पाने के लिए अपना राज्य और मिट्टी का प्रकार चुनें'
    },
    
    ta: {
        // Navigation
        'nav-home': 'முகப்பு',
        'nav-weather': 'வானிலை',
        'nav-market': 'சேமிப்பு வழிகாட்டி',
        'nav-calendar': 'பயிர் ஆலோசகர்',
        'nav-profit': 'லாப கணிப்பான்',
        'nav-inputs': 'விவசாய உள்ளீடுகள்',
        'nav-schemes': 'திட்டங்கள்',
        
        // Hero
        'hero-title': 'சிறந்த எதிர்காலத்திற்கான ஸ்மார்ட் விவசாயம்',
        'hero-subtitle': 'தொழில்நுட்பம் மற்றும் அறிவுடன் விவசாயிகளை மேம்படுத்துதல்',
        
        // Features
        'feature-weather': 'வானிலை முன்னறிவிப்பு',
        'feature-weather-desc': 'நேரடி வானிலை புதுப்பிப்புகள்',
        'feature-market': 'சேமிப்பு வழிகாட்டி',
        'feature-market-desc': 'சரியான பயிர் சேமிப்பு குறிப்புகள்',
        'feature-calendar': 'பயிர் ஆலோசகர்',
        'feature-calendar-desc': 'தனிப்பயன் பயிர் பரிந்துரைகள்',
        'feature-profit': 'லாப கணிப்பான்',
        'feature-profit-desc': 'உங்கள் வருவாயை மதிப்பிடுங்கள்',
        'feature-inputs': 'விவசாய உள்ளீடுகள்',
        'feature-inputs-desc': 'விதைகள், உரங்கள் மற்றும் பல',
        'feature-schemes': 'அரசு திட்டங்கள்',
        'feature-schemes-desc': 'நன்மைகள் மற்றும் மானியங்கள்',
        
        // Weather
        'weather-title': 'வானிலை முன்னறிவிப்பு',
        'weather-location': 'இடத்தை உள்ளிடவும்',
        
        // Market
        'market-title': 'சந்தை விலைகள்',
        'market-crop': 'பயிர்',
        'market-price': 'விலை (₹/குவிண்டால்)',
        'market-location': 'இடம்',
        'market-trend': 'போக்கு',
        
        // Crop Calendar
        'calendar-title': 'தனிப்பயன் பயிர் ஆலோசகர்',
        'crop-rice': 'நெல்',
        'crop-wheat': 'கோதுமை',
        'crop-cotton': 'பருத்தி',
        'crop-sugarcane': 'கரும்பு',
        'crop-maize': 'சோளம்',
        'crop-soybean': 'சோயாபீன்',
        'crop-groundnut': 'நிலக்கடலை',
        'crop-chickpea': 'கொண்டைக்கடலை',
        'crop-mustard': 'கடுகு',
        'crop-onion': 'வெங்காயம்',
        'crop-potato': 'உருளைக்கிழங்கு',
        'crop-tomato': 'தக்காளி',
        'crop-chilli': 'மிளகாய்',
        'crop-turmeric': 'மஞ்சள்',
        'crop-banana': 'வாழை',
        
        // Profit Calculator
        'profit-title': 'விவசாய லாப முன்னறிவிப்பான்',
        'profit-calculator': 'லாப கணிப்பான்',
        'profit-land': 'நில பரப்பு (ஏக்கர்)',
        'profit-crop': 'பயிர் பெயர்',
        'profit-yield': 'எதிர்பார்க்கப்படும் விளைச்சல் (குவிண்டால்/ஏக்கர்)',
        'profit-price': 'சந்தை விலை (₹/குவிண்டால்)',
        'profit-calculate': 'கணக்கிடு',
        'profit-production': 'மொத்த உற்பத்தி:',
        'profit-revenue': 'மதிப்பிடப்பட்ட வருவாய்:',
        'profit-profit': 'எதிர்பார்க்கப்படும் லாபம்:',
        'farm-calculator': 'விவசாய கணிப்பான்',
        
        // Farm Inputs
        'inputs-title': 'விவசாய உள்ளீடுகள்',
        'inputs-seeds': 'விதைகள்',
        'inputs-seeds-desc': 'உயர்தர சான்றளிக்கப்பட்ட விதைகள்',
        'inputs-fertilizers': 'உரங்கள்',
        'inputs-fertilizers-desc': 'கரிம மற்றும் இரசாயன உரங்கள்',
        'inputs-pesticides': 'பூச்சிக்கொல்லிகள்',
        'inputs-pesticides-desc': 'பாதுகாப்பான பூச்சி கட்டுப்பாடு தீர்வுகள்',
        'inputs-irrigation': 'நீர்ப்பாசன உபகரணங்கள்',
        'inputs-irrigation-desc': 'சொட்டு மற்றும் தெளிப்பு அமைப்புகள்',
        'inputs-machinery': 'விவசாய இயந்திரங்கள்',
        'inputs-machinery-desc': 'நவீன விவசாய உபகரணங்கள்',
        'inputs-learn': 'மேலும் அறிக',
        
        // Government Schemes
        'schemes-title': 'அரசு திட்டங்கள்',
        'scheme-pmkisan': 'பிஎம்-கிசான்',
        'scheme-pmfby': 'பிஎம் பசல் பீமா யோஜனா',
        'scheme-soil': 'மண் ஆரோக்கிய அட்டை',
        'schemes-eligibility': 'தகுதி:',
        'schemes-documents': 'தேவையான ஆவணங்கள்:',
        'schemes-benefits': 'நன்மைகள்:',
        
        // Seeds Modal
        'modal-seeds-title': '🌱 விதைகள் தகவல்',
        'modal-fertilizers-title': '🧪 உரங்கள் தகவல்',
        'modal-pesticides-title': '🐛 பூச்சிக்கொல்லிகள் தகவல்',
        'modal-irrigation-title': '💧 நீர்ப்பாசன உபகரணங்கள்',
        'modal-machinery-title': '🚜 விவசாய இயந்திரங்கள்',
        'modal-uses': 'பயன்கள்:',
        'modal-season': 'பருவம்:',
        'modal-tips': '💡 குறிப்புகள்:',
        'modal-safety': '⚠️ பாதுகாப்பு:',
        'modal-maintenance': '💡 பராமரிப்பு:',
        'seed-rice': 'நெல் விதைகள்',
        'seed-wheat': 'கோதுமை விதைகள்',
        'seed-cotton': 'பருத்தி விதைகள்',
        'seed-maize': 'சோளம் விதைகள்',
        'seed-vegetable': 'காய்கறி விதைகள்',
        'seed-pulses': 'பருப்பு விதைகள்',
        'seed-rice-use': 'முக்கிய உணவு பயிர், அதிக விளைச்சல் வகைகள்',
        'seed-wheat-use': 'மாவு உற்பத்தி, அதிக புரதம்',
        'seed-cotton-use': 'ஜவுளி தொழில், எண்ணெய் உற்பத்தி',
        'seed-maize-use': 'உணவு, கால்நடை தீவனம், தொழில்துறை',
        'seed-veg-use': 'தக்காளி, வெங்காயம், உருளைக்கிழங்கு சாகுபடி',
        'seed-pulses-use': 'புரதம் நிறைந்த உணவு, மண் வளப்படுத்துதல்',
        'season-yearround': 'ஆண்டு முழுவதும்',
        'seed-tip1': 'அங்கீகரிக்கப்பட்ட விற்பனையாளர்களிடமிருந்து சான்றளிக்கப்பட்ட விதைகளை வாங்கவும்',
        'seed-tip2': 'வாங்குவதற்கு முன் விதை முளைப்பு விகிதத்தை சரிபார்க்கவும்',
        'seed-tip3': 'விதைகளை குளிர்ந்த, உலர்ந்த இடத்தில் சேமிக்கவும்',
        'seed-tip4': 'உங்கள் மண்ணுக்கு ஏற்ற வகைகளை தேர்வு செய்யவும்',
        
        // PM-KISAN Scheme Details
        'pmkisan-desc': 'பிரதமர் கிசான் சம்மான் நிதி - ₹6000/ஆண்டு நேரடி வருமான ஆதரவு',
        'pmkisan-elig1': 'அனைத்து நில உடைமை விவசாயிகள்',
        'pmkisan-elig2': 'செல்லுபடியாகும் ஆதார் அட்டை',
        'pmkisan-doc1': 'ஆதார் அட்டை',
        'pmkisan-doc2': 'வங்கி கணக்கு விவரங்கள்',
        'pmkisan-doc3': 'நில பதிவுகள்',
        
        // PMFBY Scheme Details
        'pmfby-desc': 'பிரதமர் பசல் பீமா யோஜனா - பயிர் காப்பீட்டு திட்டம்',
        'pmfby-elig1': 'அறிவிக்கப்பட்ட பயிர்களை வளர்க்கும் அனைத்து விவசாயிகள்',
        'pmfby-elig2': 'பங்குதாரர்கள் மற்றும் குத்தகை விவசாயிகள்',
        'pmfby-ben1': 'பயிர் இழப்புக்கான காப்பீடு',
        'pmfby-ben2': 'குறைந்த பிரீமியம் விகிதங்கள்',
        
        // Soil Health Card Details
        'soil-desc': 'விரிவான மண் பகுப்பாய்வு மற்றும் பரிந்துரைகளைப் பெறுங்கள்',
        'soil-elig1': 'அனைத்து விவசாயிகள்',
        'soil-elig2': 'இலவசம்',
        'soil-ben1': 'மண் ஊட்டச்சத்து நிலை',
        'soil-ben2': 'உர பரிந்துரைகள்',
        
        // Buttons
        'btn-watch': 'YouTube இல் பார்க்கவும்',
        'btn-apply': 'ஆன்லைனில் விண்ணப்பிக்கவும்',
        
        // Fertilizers Modal
        'fert-urea': 'யூரியா (46% N)',
        'fert-urea-use': 'இலை வளர்ச்சி மற்றும் பச்சை நிறத்திற்கு நைட்ரஜன் வழங்குகிறது',
        'fert-urea-app': '50-100 கிலோ ஒரு ஏக்கருக்கு',
        'fert-dap': 'டிஏபி (18-46-0)',
        'fert-dap-use': 'பாஸ்பரஸ் நிறைந்தது, வேர் வளர்ச்சியை ஊக்குவிக்கிறது',
        'fert-dap-app': '40-80 கிலோ ஒரு ஏக்கருக்கு',
        'fert-mop': 'எம்ஓபி (பொட்டாஷ்)',
        'fert-mop-use': 'பழ தரம் மற்றும் நோய் எதிர்ப்புக்கு பொட்டாசியம்',
        'fert-mop-app': '30-60 கிலோ ஒரு ஏக்கருக்கு',
        'fert-npk': 'என்பிகே (19-19-19)',
        'fert-npk-use': 'ஒட்டுமொத்த தாவர வளர்ச்சிக்கு சமச்சீர் ஊட்டச்சத்து',
        'fert-npk-app': '50-100 கிலோ ஒரு ஏக்கருக்கு',
        'fert-compost': 'கம்போஸ்ட்',
        'fert-compost-use': 'கரிமப் பொருள், மண் அமைப்பை மேம்படுத்துகிறது',
        'fert-compost-app': '2-5 டன் ஒரு ஏக்கருக்கு',
        'fert-vermi': 'மண்புழு உரம்',
        'fert-vermi-use': 'வளமான கரிம உரம், மண் வளத்தை அதிகரிக்கிறது',
        'fert-vermi-app': '1-2 டன் ஒரு ஏக்கருக்கு',
        'fert-zinc': 'துத்தநாக சல்பேட்',
        'fert-zinc-use': 'துத்தநாக குறைபாட்டை சரிசெய்கிறது, பயிர் விளைச்சலை மேம்படுத்துகிறது',
        'fert-zinc-app': '10-25 கிலோ ஒரு ஏக்கருக்கு',
        'fert-calcium': 'கால்சியம் நைட்ரேட்',
        'fert-calcium-use': 'கால்சியம் மற்றும் நைட்ரஜன் வழங்குகிறது, பூ அழுகலை தடுக்கிறது',
        'fert-calcium-app': '20-40 கிலோ ஒரு ஏக்கருக்கு',
        'fert-sulphur': 'கந்தகம்',
        'fert-sulphur-use': 'புரத தொகுப்புக்கு அவசியம், எண்ணெய் உள்ளடக்கத்தை மேம்படுத்துகிறது',
        'fert-sulphur-app': '15-30 கிலோ ஒரு ஏக்கருக்கு',
        'fert-boron': 'போரான்',
        'fert-boron-use': 'பூக்கும், பழம் உருவாக்கம் மற்றும் விதை உருவாக்கத்தை மேம்படுத்துகிறது',
        'fert-boron-app': '5-10 கிலோ ஒரு ஏக்கருக்கு',
        'fert-tip1': 'பயன்படுத்துவதற்கு முன் மண் பரிசோதனை செய்யவும்',
        'fert-tip2': 'சரியான நேரத்தில் பயன்படுத்தவும்',
        'fert-tip3': 'கரிம மற்றும் இரசாயன கலவை',
        'fert-tip4': 'அதிக உரமிடுதலை தவிர்க்கவும்',
        'modal-application': 'பயன்பாடு:',
        
        // Pesticides Modal
        'pest-chlorpyrifos': 'குளோர்பைரிபாஸ்',
        'pest-chlorpyrifos-use': 'கரையான், அசுவினிகள் மற்றும் மண் பூச்சிகளை கட்டுப்படுத்துகிறது',
        'pest-chlorpyrifos-app': '400-500 மிலி ஒரு ஏக்கருக்கு',
        'pest-imidacloprid': 'இமிடாக்ளோபிரிட்',
        'pest-imidacloprid-use': 'வெள்ளை ஈ போன்ற உறிஞ்சும் பூச்சிகளுக்கு எதிராக பயனுள்ளது',
        'pest-imidacloprid-app': '100-150 மிலி ஒரு ஏக்கருக்கு',
        'pest-cypermethrin': 'சைபர்மெத்ரின்',
        'pest-cypermethrin-use': 'பருத்தி புழு, கம்பளிப்பூச்சி மற்றும் வண்டுகளை கட்டுப்படுத்துகிறது',
        'pest-cypermethrin-app': '200-300 மிலி ஒரு ஏக்கருக்கு',
        'pest-neem': 'வேப்ப எண்ணெய்',
        'pest-neem-use': 'பல்வேறு பூச்சிகள் மற்றும் நோய்களுக்கு கரிம பூச்சிக்கொல்லி',
        'pest-neem-app': '1-2 லிட்டர் ஒரு ஏக்கருக்கு',
        'pest-mancozeb': 'மான்கோசெப்',
        'pest-mancozeb-use': 'கருகல், துரு மற்றும் இலை புள்ளிகளுக்கு பூஞ்சைக்கொல்லி',
        'pest-mancozeb-app': '400-600 கிராம் ஒரு ஏக்கருக்கு',
        'pest-carbendazim': 'கார்பென்டாசிம்',
        'pest-carbendazim-use': 'விதை சிகிச்சைக்கு பரந்த-ஸ்பெக்ட்ரம் பூஞ்சைக்கொல்லி',
        'pest-carbendazim-app': '200-250 கிராம் ஒரு ஏக்கருக்கு',
        'pest-bt': 'பாசிலஸ் துரிஞ்சியென்சிஸ்',
        'pest-bt-use': 'கம்பளிப்பூச்சி மற்றும் லார்வாக்களுக்கு உயிரியல் பூச்சிக்கொல்லி',
        'pest-bt-app': '200-400 கிராம் ஒரு ஏக்கருக்கு',
        'pest-profenofos': 'ப்ரோபெனோபாஸ்',
        'pest-profenofos-use': 'பருத்தி புழு, ஜாசிட்ஸ் மற்றும் த்ரிப்ஸ் கட்டுப்படுத்துகிறது',
        'pest-profenofos-app': '400-500 மிலி ஒரு ஏக்கருக்கு',
        'pest-glyphosate': 'கிளைபோசேட்',
        'pest-glyphosate-use': 'பயிர்களில் களை கட்டுப்பாட்டுக்கு களைக்கொல்லி',
        'pest-glyphosate-app': '1-1.5 லிட்டர் ஒரு ஏக்கருக்கு',
        'pest-acetamiprid': 'அசிடாமிப்ரிட்',
        'pest-acetamiprid-use': 'அசுவினிகள், ஜாசிட்ஸ் மற்றும் வெள்ளை ஈ கட்டுப்படுத்துகிறது',
        'pest-acetamiprid-app': '60-80 கிராம் ஒரு ஏக்கருக்கு',
        'pest-tip1': 'பாதுகாப்பு உபகரணங்களை அணியவும்',
        'pest-tip2': 'லேபிள் வழிமுறைகளை படிக்கவும்',
        'pest-tip3': 'காலை/மாலை தெளிக்கவும்',
        'pest-tip4': 'குழந்தைகளிடமிருந்து விலக்கவும்',
        
        // Irrigation Modal
        'irr-drip': 'சொட்டு நீர்ப்பாசனம்',
        'irr-drip-use': 'வரிசை பயிர்கள் மற்றும் தோட்டங்களுக்கு நீர்-திறனுள்ள அமைப்பு',
        'irr-drip-ben': '40-70% நீரை சேமிக்கிறது, களை வளர்ச்சியை குறைக்கிறது',
        'irr-sprinkler': 'தெளிப்பு அமைப்பு',
        'irr-sprinkler-use': 'அனைத்து பயிர்களுக்கும் ஏற்றது, குறிப்பாக காய்கறிகள்',
        'irr-sprinkler-ben': 'சீரான நீர் விநியோகம், உழைப்பை சேமிக்கிறது',
        'irr-micro': 'மைக்ரோ ஸ்ப்ரிங்க்லர்',
        'irr-micro-use': 'பழ மரங்கள் மற்றும் தோட்ட பயிர்களுக்கு ஏற்றது',
        'irr-micro-ben': 'குறைந்த அழுத்தம் தேவை, பெரிய பகுதியை உள்ளடக்குகிறது',
        'irr-submersible': 'நீரில் மூழ்கும் பம்ப்',
        'irr-submersible-use': 'நீர்ப்பாசனத்திற்கு ஆழமான கிணற்று நீர் எடுத்தல்',
        'irr-submersible-ben': 'உயர் திறன், குறைந்த பராமரிப்பு',
        'irr-centrifugal': 'மையவிலக்கு பம்ப்',
        'irr-centrifugal-use': 'நீர்ப்பாசனத்திற்கு மேற்பரப்பு நீர் பம்பிங்',
        'irr-centrifugal-ben': 'செலவு குறைவு, இயக்க எளிதானது',
        'irr-solar': 'சூரிய பம்ப்',
        'irr-solar-use': 'சூரிய ஆற்றலைப் பயன்படுத்தி சுற்றுச்சூழல் நட்பு நீர்ப்பாசனம்',
        'irr-solar-ben': 'மின்சாரம் இலவசம், சுற்றுச்சூழல் நட்பு',
        'irr-pipes': 'பிவிசி குழாய்கள்',
        'irr-pipes-use': 'நீர்ப்பாசன அமைப்புகளில் நீர் விநியோகம்',
        'irr-pipes-ben': 'நீடித்த, அரிப்பு-எதிர்ப்பு, இலகுவான',
        'irr-filter': 'நீர் வடிகட்டி',
        'irr-filter-use': 'நீர்ப்பாசன நீரிலிருந்து அசுத்தங்களை நீக்குகிறது',
        'irr-filter-ben': 'அடைப்பை தடுக்கிறது, அமைப்பு ஆயுளை நீட்டிக்கிறது',
        'irr-timer': 'நீர்ப்பாசன டைமர்',
        'irr-timer-use': 'தானியங்கு நீர்ப்பாசன திட்டமிடல்',
        'irr-timer-ben': 'நேரத்தை சேமிக்கிறது, சரியான நேரத்தில் நீர்ப்பாசனம் உறுதி செய்கிறது',
        'irr-meter': 'நீர் மீட்டர்',
        'irr-meter-use': 'நீர்ப்பாசனத்தில் நீர் பயன்பாட்டை அளவிடுகிறது',
        'irr-meter-ben': 'நீர் நுகர்வை மேம்படுத்த உதவுகிறது',
        'irr-tip1': 'பயிர் வகையின் அடிப்படையில் தேர்வு செய்யவும்',
        'irr-tip2': 'வழக்கமான பராமரிப்பு',
        'irr-tip3': 'நீர் சேமிப்புக்கு சொட்டு நீர் பயன்படுத்தவும்',
        'irr-tip4': 'காலை/மாலை நீர்ப்பாசனம் செய்யவும்',
        'modal-benefits': 'நன்மைகள்:',
        
        // Machinery Modal
        'mach-tractor': 'டிராக்டர்',
        'mach-tractor-use': 'பல்வேறு விவசாய செயல்பாடுகளுக்கான முதன்மை சக்தி மூலம்',
        'mach-tractor-ben': 'பல்துறை, உழைப்பை குறைக்கிறது, திறனை அதிகரிக்கிறது',
        'mach-rotavator': 'ரோட்டவேட்டர்',
        'mach-rotavator-use': 'மண் தயாரிப்பு, பயிர் எச்சங்களை கலத்தல்',
        'mach-rotavator-ben': 'நேரத்தை சேமிக்கிறது, மண் அமைப்பை மேம்படுத்துகிறது',
        'mach-seeddrill': 'விதை துளையிடும் கருவி',
        'mach-seeddrill-use': 'சீரான ஆழத்தில் துல்லியமான விதை விதைத்தல்',
        'mach-seeddrill-ben': 'சீரான முளைப்பு, விதைகளை சேமிக்கிறது',
        'mach-sprayer': 'பவர் ஸ்ப்ரேயர்',
        'mach-sprayer-use': 'பூச்சிக்கொல்லி மற்றும் உர பயன்பாடு',
        'mach-sprayer-ben': 'சீரான கவரேஜ், இரசாயனங்களை சேமிக்கிறது',
        'mach-harvester': 'அறுவடை இயந்திரம்',
        'mach-harvester-use': 'பயிர் அறுவடை மற்றும் கதிரடித்தல்',
        'mach-harvester-ben': 'விரைவான அறுவடை, தானிய இழப்பை குறைக்கிறது',
        'mach-cultivator': 'கல்டிவேட்டர்',
        'mach-cultivator-use': 'களை கட்டுப்பாடு மற்றும் மண் காற்றோட்டம்',
        'mach-cultivator-ben': 'மண் ஆரோக்கியத்தை மேம்படுத்துகிறது, களைகளை நீக்குகிறது',
        'mach-thresher': 'கதிரடிக்கும் இயந்திரம்',
        'mach-thresher-use': 'பயிர் தண்டுகளிலிருந்து தானியங்களை பிரித்தல்',
        'mach-thresher-ben': 'விரைவான செயலாக்கம், கைமுறை உழைப்பை குறைக்கிறது',
        'mach-chaff': 'தீவன வெட்டி',
        'mach-chaff-use': 'கால்நடைகளுக்கு தீவனம் வெட்டுதல்',
        'mach-chaff-ben': 'எளிதான உணவளித்தல், வீணாக்கத்தை குறைக்கிறது',
        'mach-dryer': 'தானிய உலர்த்தி',
        'mach-dryer-use': 'சேமிப்புக்காக அறுவடை செய்த தானியங்களை உலர்த்துதல்',
        'mach-dryer-ben': 'கெட்டுப்போவதை தடுக்கிறது, தரத்தை பராமரிக்கிறது',
        'mach-mulcher': 'மல்ச்சர்',
        'mach-mulcher-use': 'பயிர் எச்சங்கள் மற்றும் களைகளை நறுக்குதல்',
        'mach-mulcher-ben': 'மண் வளப்படுத்துதல், ஈரப்பதம் தக்கவைத்தல்',
        'mach-tip1': 'வழக்கமான சேவை தேவை',
        'mach-tip2': 'சரியான இயக்குனர் பயிற்சி',
        'mach-tip3': 'உலர்ந்த இடத்தில் சேமிக்கவும்',
        'mach-tip4': 'ஒவ்வொரு பயன்பாட்டிற்கு முன்பும் சரிபார்க்கவும்',
        
        // Calendar Legend
        'legend-sowing': 'விதைத்தல்',
        'legend-fertilizer': 'உரமிடுதல்',
        'legend-harvest': 'அறுவடை',

        // Crop Advisor
        'advisor-state': 'மாநிலம் தேர்ந்தெடுக்கவும்',
        'advisor-month': 'தற்போதைய மாதம்',
        'advisor-soil': 'மண் வகை',
        'advisor-placeholder': 'தனிப்பயன் பயிர் பரிந்துரைகளைப் பெற உங்கள் மாநிலம் மற்றும் மண் வகையை தேர்ந்தெடுக்கவும்'
    }
};

function changeLanguage() {
    const lang = document.getElementById('languageSelect').value;
    const elements = document.querySelectorAll('[data-lang]');
    
    elements.forEach(el => {
        const key = el.getAttribute('data-lang');
        if (translations[lang] && translations[lang][key]) {
            if (el.tagName === 'INPUT') {
                el.placeholder = translations[lang][key];
            } else {
                el.textContent = translations[lang][key];
            }
        }
    });

    // Re-render crop advisor in new language
    if (typeof getCropAdvice === 'function') {
        getCropAdvice();
    }
    // Re-render storage guide in new language
    if (typeof showStorageGuide === 'function') {
        showStorageGuide();
    }
}
